### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by micheleberardi** [devartis/passbook#48]
Hi
first at all thanks for the script 

i tried to run my script on python 3 but I got the following error

someone can help me?

 python3 generate.py 
Traceback (most recent call last):
  File "generate.py", line 25, in <module>
    passfile.create('certificate.pem', 'key.pem', 'wwdr.pem', password , 'test.pkpass')
  File "/var/www/html/source/pass.bucksense.com/passbook-master/passbook/models.py", line 319, in create
    manifest = self._createManifest(pass_json)
  File "/var/www/html/source/pass.bucksense.com/passbook-master/passbook/models.py", line 332, in _createManifest
    self._hashes['pass.json'] = hashlib.sha1(pass_json).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

**Comment by micheleberardi** [comment]
sorry m mistake i fixed
